#!/usr/bin/env python3
"""
Build Neo4j CIDOC-CRM data with persistent place identities.

Fork of build_neo4j_cidoc_crm.py that uses persistent_places_output/
to correctly assign E53_Place nodes to persistent geographic entities
instead of raw TCP UIDs.

v2 conventions:
- e53_place_csd.csv: place_id = persistent_place_id (not raw tcpuid)
- p166_was_presence_of_*.csv: :END_ID = persistent_place_id

C3 changes (no edge properties; see docs/P122_PRESENCE_LEVEL_DECISION.md):
- p89_falls_within_*.csv: DROPPED. Redundant with p10_csd_within_cd_presence_*
  (generated by build_cd_presences.py), which expresses the same hierarchy
  at the presence level without edge properties.
- p122_borders_with_*.csv: REWRITTEN. Edges now run between E93_Presence
  nodes ({tcpuid}_{year}). Border length is reified as an E16_Measurement
  cluster emitted to:
    * e16_border_measurement_{year}.csv
    * e54_border_dimension_{year}.csv
    * p39_measured_border_{year}.csv  (E16 → E93_Presence)
    * p40_observed_dimension_border_{year}.csv  (E16 → E54)
    * p91_has_unit_border_{year}.csv  (E54 → E58)
  Plus a single e58_measurement_unit.csv with the metre row.

Unchanged:
- e93_presence_*.csv (presence IDs keep {tcpuid}_{year} format)
- e94_space_primitive_*.csv (centroid IDs unchanged)
- e4_period.csv (census periods unchanged)
- p164_temporally_specified_by_*.csv (presence→period unchanged)
- p161_has_spatial_projection_*.csv (presence→centroid unchanged)
"""

import csv
import geopandas as gpd
import pandas as pd
from pathlib import Path
from shapely import make_valid
import argparse
import sys
from typing import Dict, Set, Tuple


def load_persistent_place_mapping(places_dir: Path) -> Tuple[dict, pd.DataFrame]:
    """
    Load persistent place mapping and registry.

    Returns:
        (mapping, registry_df)
        mapping: dict of (tcpuid, year) -> persistent_place_id
        registry_df: DataFrame of persistent place registry
    """
    mapping_file = places_dir / "tcpuid_year_to_place.csv"
    registry_file = places_dir / "persistent_place_registry.csv"

    mapping_df = pd.read_csv(mapping_file)
    registry_df = pd.read_csv(registry_file)

    # Build lookup dict
    mapping = {}
    for _, row in mapping_df.iterrows():
        mapping[(row["tcpuid"], int(row["year"]))] = row["persistent_place_id"]

    print(f"  Loaded {len(mapping)} (tcpuid, year) -> persistent_place_id mappings", file=sys.stderr)
    print(f"  Loaded {len(registry_df)} persistent places from registry", file=sys.stderr)
    return mapping, registry_df


def load_year_layer(gdb_path: str, year: int) -> gpd.GeoDataFrame:
    """Load CSD layer for a specific year from FileGDB."""
    if year == 1911:
        layer_name = f"CANADA_{year}_CSD_V2T2"
    else:
        layer_name = f"CANADA_{year}_CSD"
    print(f"Loading {layer_name}...", file=sys.stderr)

    gdf = gpd.read_file(gdb_path, layer=layer_name)

    # Standardize column names
    rename_map = {}
    for col in gdf.columns:
        if col == f'TCPUID_CSD_{year}' or col == f'V2t2_UID_{year}':
            rename_map[col] = 'tcpuid'
        elif col == f'PR_{year}':
            rename_map[col] = 'pr'
        elif col in [f'Name_CD_{year}', f'NAME_CD_{year}']:
            rename_map[col] = 'cd_name'
        elif col in [f'Name_CSD_{year}', f'NAME_CSD_{year}']:
            rename_map[col] = 'csd_name'

    gdf = gdf.rename(columns=rename_map)
    cols_to_keep = ['tcpuid', 'pr', 'cd_name', 'csd_name', 'geometry']
    gdf = gdf[cols_to_keep]

    # Validate geometries
    invalid_mask = ~gdf.is_valid
    if invalid_mask.any():
        print(f"  Fixing {invalid_mask.sum()} invalid geometries...", file=sys.stderr)
        gdf.loc[invalid_mask, 'geometry'] = gdf.loc[invalid_mask, 'geometry'].apply(make_valid)

    # Reproject to EPSG:3347
    if gdf.crs is None or gdf.crs.to_epsg() != 3347:
        print(f"  Reprojecting to EPSG:3347...", file=sys.stderr)
        gdf = gdf.to_crs(epsg=3347)

    gdf['area'] = gdf.geometry.area
    print(f"  Loaded {len(gdf)} CSDs", file=sys.stderr)
    return gdf


def resolve_place_id(tcpuid: str, year: int, mapping: dict, fallback_places: dict,
                     name: str = '', province: str = '') -> str:
    """
    Look up persistent_place_id for a (tcpuid, year).
    If not found in mapping (singleton not in year_links), create a fallback.
    """
    key = (tcpuid, year)
    if key in mapping:
        return mapping[key]

    # Fallback for CSDs not in any year_links (appeared in only one year
    # with no spatial overlap to adjacent census years)
    fallback_id = f"PLACE_{tcpuid}_{year}"
    if fallback_id not in fallback_places:
        fallback_places[fallback_id] = {'name': name, 'province': province, 'year': year}
    return fallback_id


def extract_e93_presences(gdf: gpd.GeoDataFrame, year: int) -> pd.DataFrame:
    """E93_Presence nodes - unchanged from v1."""
    print(f"  Extracting E93_Presence nodes for {year}...", file=sys.stderr)
    return pd.DataFrame({
        'presence_id:ID': gdf['tcpuid'] + f'_{year}',
        'csd_tcpuid': gdf['tcpuid'],
        'census_year:int': year,
        'area_sqm:float': gdf['area'].round(2),
        ':LABEL': 'E93_Presence'
    })


def extract_e94_space_primitives(gdf: gpd.GeoDataFrame, year: int) -> pd.DataFrame:
    """E94_Space_Primitive nodes - unchanged from v1."""
    print(f"  Computing E94_Space_Primitive (centroids) for {year}...", file=sys.stderr)
    centroids_3347 = gdf.geometry.centroid
    centroids_latlon = centroids_3347.to_crs(epsg=4326)
    return pd.DataFrame({
        'space_id:ID': gdf['tcpuid'] + f'_{year}_centroid',
        'latitude:float': centroids_latlon.y.round(6),
        'longitude:float': centroids_latlon.x.round(6),
        'crs': 'EPSG:4326',
        ':LABEL': 'E94_Space_Primitive'
    })


def extract_p166_was_presence_of(gdf: gpd.GeoDataFrame, year: int,
                                  mapping: dict, fallback_places: dict) -> pd.DataFrame:
    """P166: E93_Presence -> E53_Place (using persistent place IDs)."""
    print(f"  Creating P166_was_a_presence_of relationships...", file=sys.stderr)
    place_ids = [
        resolve_place_id(uid, year, mapping, fallback_places,
                         name=row['csd_name'], province=row['pr'])
        for uid, (_, row) in zip(gdf['tcpuid'], gdf.iterrows())
    ]
    return pd.DataFrame({
        ':START_ID': gdf['tcpuid'] + f'_{year}',
        ':END_ID': place_ids,
        ':TYPE': 'P166_was_a_presence_of'
    })


def extract_p164_temporally_specified_by(gdf: gpd.GeoDataFrame, year: int) -> pd.DataFrame:
    """P164: E93_Presence -> E4_Period - unchanged from v1."""
    print(f"  Creating P164_is_temporally_specified_by relationships...", file=sys.stderr)
    return pd.DataFrame({
        ':START_ID': gdf['tcpuid'] + f'_{year}',
        ':END_ID': f'CENSUS_{year}',
        ':TYPE': 'P164_is_temporally_specified_by'
    })


def extract_p4_has_time_span(gdf: gpd.GeoDataFrame, year: int) -> pd.DataFrame:
    """P4: E93_Presence -> E52_Time-Span (M5: explicit ISO 8601 bounds)."""
    print(f"  Creating P4_has_time-span relationships...", file=sys.stderr)
    return pd.DataFrame({
        ':START_ID': gdf['tcpuid'] + f'_{year}',
        ':END_ID': f'TIMESPAN_{year}',
        ':TYPE': 'P4_has_time-span'
    })


def extract_p161_spatial_projection(gdf: gpd.GeoDataFrame, year: int) -> pd.DataFrame:
    """P161: E93_Presence -> E94_Space_Primitive - unchanged from v1."""
    print(f"  Creating P161_has_spatial_projection relationships...", file=sys.stderr)
    return pd.DataFrame({
        ':START_ID': gdf['tcpuid'] + f'_{year}',
        ':END_ID': gdf['tcpuid'] + f'_{year}_centroid',
        ':TYPE': 'P161_has_spatial_projection'
    })


def extract_p122_borders_reified(gdf: gpd.GeoDataFrame, year: int) -> dict:
    """
    Compute CSD-to-CSD borders for `year` and emit them in the reified form
    that survives RDF export (no edge properties).

    For each touching pair (A, B) with a shared boundary length > 1 metre:

        A_{year} --P122_borders_with--> B_{year}       (plain edge, no props)

        E16_Measurement BORDER_MEAS_A_B_{year}
            P39_measured         -> A_{year}
            P40_observed_dimension -> BORDER_DIM_A_B_{year}

        E54_Dimension BORDER_DIM_A_B_{year}
            P90_has_value   = <length_metres>
            P91_has_unit    -> UNIT_METRE

    Returns a dict of DataFrames keyed by CSV stem. The E58_Measurement_Unit
    node itself is shared across years and written once by main().

    Endpoints are E93_Presence IDs ({tcpuid}_{year}) per the presence-level
    modelling decision (see docs/P122_PRESENCE_LEVEL_DECISION.md).
    """
    print(f"  Computing P122_borders_with (reified) for {year}...", file=sys.stderr)

    p122_edges = []
    e16_rows = []
    e54_rows = []
    p39_rows = []
    p40_rows = []
    p91_rows = []

    sindex = gdf.sindex

    for idx, row in gdf.iterrows():
        geom = row['geometry']
        tcpuid = row['tcpuid']
        presence_a = f"{tcpuid}_{year}"

        possible_neighbors = list(sindex.intersection(geom.bounds))

        for neighbor_idx in possible_neighbors:
            if neighbor_idx == idx:
                continue

            neighbor_row = gdf.iloc[neighbor_idx]
            neighbor_geom = neighbor_row['geometry']
            neighbor_tcpuid = neighbor_row['tcpuid']

            # Avoid duplicates (only A->B, not B->A) using lexical order of
            # raw tcpuids so the canonical direction is stable across runs.
            if tcpuid >= neighbor_tcpuid:
                continue

            if not geom.touches(neighbor_geom):
                continue

            try:
                intersection = geom.boundary.intersection(neighbor_geom.boundary)
                border_length = intersection.length
            except Exception as e:
                print(f"  Warning: Border computation error: {e}", file=sys.stderr)
                continue

            if border_length <= 1.0:
                continue

            presence_b = f"{neighbor_tcpuid}_{year}"
            length_m = round(border_length, 2)

            # Stable, unambiguous IDs for the measurement cluster.
            # Includes year because the same pair of CSDs may share a border
            # in multiple census years with different lengths.
            meas_id = f"BORDER_MEAS_{tcpuid}_{neighbor_tcpuid}_{year}"
            dim_id = f"BORDER_DIM_{tcpuid}_{neighbor_tcpuid}_{year}"

            p122_edges.append({
                ':START_ID': presence_a,
                ':END_ID': presence_b,
                ':TYPE': 'P122_borders_with',
            })
            e16_rows.append({
                'measurement_id:ID': meas_id,
                ':LABEL': 'E16_Measurement',
                'measurement_type': 'shared_border_length',
                'year:int': year,
            })
            e54_rows.append({
                'dimension_id:ID': dim_id,
                ':LABEL': 'E54_Dimension',
                'value:float': length_m,
                'dimension_type': 'length',
            })
            p39_rows.append({
                ':START_ID': meas_id,
                ':END_ID': presence_a,
                ':TYPE': 'P39_measured',
            })
            p40_rows.append({
                ':START_ID': meas_id,
                ':END_ID': dim_id,
                ':TYPE': 'P40_observed_dimension',
            })
            p91_rows.append({
                ':START_ID': dim_id,
                ':END_ID': 'UNIT_METRE',
                ':TYPE': 'P91_has_unit',
            })

        if (idx + 1) % 500 == 0:
            print(f"    Processed {idx + 1}/{len(gdf)} CSDs...", file=sys.stderr)

    print(f"  Found {len(p122_edges)} border relationships", file=sys.stderr)

    return {
        f'p122_borders_with_{year}': pd.DataFrame(p122_edges),
        f'e16_border_measurement_{year}': pd.DataFrame(e16_rows),
        f'e54_border_dimension_{year}': pd.DataFrame(e54_rows),
        f'p39_measured_border_{year}': pd.DataFrame(p39_rows),
        f'p40_observed_dimension_border_{year}': pd.DataFrame(p40_rows),
        f'p91_has_unit_border_{year}': pd.DataFrame(p91_rows),
    }


def process_year(gdb_path: str, year: int, out_dir: Path,
                 mapping: dict, fallback_places: dict,
                 all_cd_places: set,
                 cd_chain_map: dict = None):
    """Process a single census year."""
    print(f"\n{'='*60}", file=sys.stderr)
    print(f"Processing year {year}", file=sys.stderr)
    print(f"{'='*60}", file=sys.stderr)

    gdf = load_year_layer(gdb_path, year)
    stats = {}

    # E93_Presence nodes (unchanged)
    presences = extract_e93_presences(gdf, year)
    presences.to_csv(out_dir / f'e93_presence_{year}.csv', index=False)
    stats['presences'] = len(presences)
    print(f"  Wrote {len(presences)} E93_Presence nodes")

    # E94_Space_Primitive nodes (unchanged)
    space_primitives = extract_e94_space_primitives(gdf, year)
    space_primitives.to_csv(out_dir / f'e94_space_primitive_{year}.csv', index=False)
    stats['space_primitives'] = len(space_primitives)
    print(f"  Wrote {len(space_primitives)} E94_Space_Primitive nodes")

    # Collect CD places. Apply chain mapping when available so that
    # e53_place_cd.csv ends up keyed by chain place_id (post-Phase-1)
    # rather than by year-name. Singletons not in the chain registry
    # fall through to the raw cd_id and are emitted unchanged.
    for _, row in gdf[['cd_name', 'pr']].drop_duplicates().iterrows():
        raw_cd_id = f"CD_{row['pr']}_{row['cd_name'].replace(' ', '_')}"
        chain_id = (cd_chain_map or {}).get((raw_cd_id, year), raw_cd_id)
        all_cd_places.add((chain_id, row['cd_name'], row['pr']))

    # P166: Presence -> Place (using persistent IDs)
    p166 = extract_p166_was_presence_of(gdf, year, mapping, fallback_places)
    p166.to_csv(out_dir / f'p166_was_presence_of_{year}.csv', index=False)
    stats['p166'] = len(p166)
    print(f"  Wrote {len(p166)} P166_was_a_presence_of relationships")

    # P164: Presence -> Period (unchanged)
    p164 = extract_p164_temporally_specified_by(gdf, year)
    p164.to_csv(out_dir / f'p164_temporally_specified_by_{year}.csv', index=False)
    stats['p164'] = len(p164)
    print(f"  Wrote {len(p164)} P164_is_temporally_specified_by relationships")

    # P4: Presence -> Time-Span (M5: explicit ISO bounds)
    p4_ts = extract_p4_has_time_span(gdf, year)
    p4_ts.to_csv(out_dir / f'p4_has_time_span_{year}.csv', index=False)
    stats['p4_time_span'] = len(p4_ts)
    print(f"  Wrote {len(p4_ts)} P4_has_time-span relationships")

    # P161: Presence -> Space Primitive (unchanged)
    p161 = extract_p161_spatial_projection(gdf, year)
    p161.to_csv(out_dir / f'p161_spatial_projection_{year}.csv', index=False)
    stats['p161'] = len(p161)
    print(f"  Wrote {len(p161)} P161_has_spatial_projection relationships")

    # P89 is dropped as of C3 — the presence-level P10_falls_within generated
    # by build_cd_presences.py expresses the same CSD->CD hierarchy without
    # edge properties. See docs/P122_PRESENCE_LEVEL_DECISION.md.

    # P122: E93_Presence -> E93_Presence borders, with length reified as
    # E16_Measurement -> E54_Dimension -> E58_Measurement_Unit.
    p122_bundle = extract_p122_borders_reified(gdf, year)
    for stem, df in p122_bundle.items():
        df.to_csv(out_dir / f'{stem}.csv', index=False)
        print(f"  Wrote {len(df)} rows -> {stem}.csv")
    stats['p122_edges'] = len(p122_bundle[f'p122_borders_with_{year}'])
    stats['border_measurements'] = len(p122_bundle[f'e16_border_measurement_{year}'])

    return stats


def main():
    parser = argparse.ArgumentParser(
        description="Build Neo4j CIDOC-CRM data with persistent place identities"
    )
    parser.add_argument('--gdb', required=True, help='Path to TCP FileGDB')
    parser.add_argument(
        '--years',
        default='1851,1861,1871,1881,1891,1901,1911,1921',
        help='Comma-separated census years'
    )
    parser.add_argument('--out', default='neo4j_cidoc_crm_v2', help='Output directory')
    parser.add_argument(
        '--persistent-places',
        default='persistent_places_output',
        help='Directory with persistent place registry files'
    )
    parser.add_argument(
        '--cd-chains',
        default='persistent_cds_output',
        help='Directory with persistent CD chain registry + lineage'
    )

    args = parser.parse_args()

    years = [int(y.strip()) for y in args.years.split(',')]
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    places_dir = Path(args.persistent_places)

    # Load persistent place mapping
    print(f"\n{'='*60}", file=sys.stderr)
    print(f"Loading persistent place registry", file=sys.stderr)
    print(f"{'='*60}", file=sys.stderr)
    mapping, registry_df = load_persistent_place_mapping(places_dir)
    fallback_places = {}  # Track CSDs not in any year_links

    # Load CD chain mapping + registry (Phase 1 outputs).
    cd_chains_dir = Path(args.cd_chains)
    cd_chain_map = {}
    cd_chain_registry_df = None
    cd_chain_mapping_path = cd_chains_dir / "cd_id_year_to_chain.csv"
    cd_chain_registry_path = cd_chains_dir / "persistent_cd_registry.csv"
    if cd_chain_mapping_path.exists():
        with cd_chain_mapping_path.open() as f:
            for r in csv.DictReader(f):
                cd_chain_map[(r["raw_cd_id"], int(r["year"]))] = r["chain_place_id"]
        print(f"  Loaded {len(cd_chain_map):,} CD chain mappings from "
              f"{cd_chain_mapping_path.relative_to(cd_chains_dir.parent)}",
              file=sys.stderr)
    else:
        print(f"  Warning: {cd_chain_mapping_path} not found - CD chains "
              f"disabled, will mint year-name CDs (pre-Phase-1 behavior)",
              file=sys.stderr)
    if cd_chain_registry_path.exists():
        cd_chain_registry_df = pd.read_csv(cd_chain_registry_path)

    # E4_Period nodes (unchanged)
    print(f"\n{'='*60}", file=sys.stderr)
    print(f"Creating E4_Period and E52_Time-Span nodes", file=sys.stderr)
    print(f"{'='*60}", file=sys.stderr)
    periods = pd.DataFrame({
        'period_id:ID': [f'CENSUS_{y}' for y in years],
        'year:int': years,
        'label': [f'{y} Canadian Census' for y in years],
        ':LABEL': 'E4_Period'
    })
    periods.to_csv(out_dir / 'e4_period.csv', index=False)
    print(f"  Wrote {len(periods)} E4_Period nodes")

    # E52_Time-Span nodes (M5: one per census year, shared across presences
    # and measurements). The same TIMESPAN_YYYY IDs are also created by
    # build_census_observations_v2.py — they must be idempotent.
    timespans = pd.DataFrame({
        'timespan_id:ID': [f'TIMESPAN_{y}' for y in years],
        ':LABEL': 'E52_Time-Span',
        'label': [f'Census Year {y}' for y in years],
        'begin_of_begin': [f'{y}-01-01' for y in years],
        'end_of_end': [f'{y}-12-31' for y in years],
    })
    timespans.to_csv(out_dir / 'e52_timespans.csv', index=False)
    print(f"  Wrote {len(timespans)} E52_Time-Span nodes")

    # P4: E4_Period -> E52_Time-Span (link census events to their date bounds)
    p4_period_ts = pd.DataFrame({
        ':START_ID': [f'CENSUS_{y}' for y in years],
        ':END_ID': [f'TIMESPAN_{y}' for y in years],
        ':TYPE': 'P4_has_time-span',
    })
    p4_period_ts.to_csv(out_dir / 'p4_period_timespan.csv', index=False)
    print(f"  Wrote {len(p4_period_ts)} P4 period→timespan relationships")

    # E58_Measurement_Unit: shared across all years. Just one node (metre),
    # grounded to Wikidata Q11573 via owl:sameAs in the RDF export layer.
    e58 = pd.DataFrame([{
        'unit_id:ID': 'UNIT_METRE',
        ':LABEL': 'E58_Measurement_Unit',
        'label': 'metre',
        'symbol': 'm',
        'wikidata_qid': 'Q11573',
    }])
    e58.to_csv(out_dir / 'e58_measurement_unit.csv', index=False)
    print(f"  Wrote {len(e58)} E58_Measurement_Unit node(s)")

    # Process each year
    all_cd_places = set()
    total_stats = {
        k: 0 for k in [
            'presences', 'space_primitives', 'p166', 'p164', 'p4_time_span',
            'p161', 'p122_edges', 'border_measurements',
        ]
    }

    for year in years:
        stats = process_year(args.gdb, year, out_dir, mapping, fallback_places,
                             all_cd_places, cd_chain_map)
        for key in total_stats:
            total_stats[key] += stats[key]

    # E53_Place nodes (CSD) - from persistent place registry + fallbacks
    print(f"\n{'='*60}", file=sys.stderr)
    print(f"Creating E53_Place nodes (persistent)", file=sys.stderr)
    print(f"{'='*60}", file=sys.stderr)

    # Start with registry places
    csd_places = []
    for _, row in registry_df.iterrows():
        csd_places.append({
            'place_id:ID': row['persistent_place_id'],
            'name': row['canonical_name'],
            'province': row['province'],
            'place_type': 'CSD',
            'years_active': row['years_active'],
            ':LABEL': 'E53_Place'
        })

    # Add fallback places (not in year_links) - name/province collected during processing
    print(f"  Fallback places (not in year_links): {len(fallback_places)}", file=sys.stderr)
    for place_id, info in fallback_places.items():
        csd_places.append({
            'place_id:ID': place_id,
            'name': info['name'],
            'province': info['province'],
            'place_type': 'CSD',
            'years_active': str(info['year']),
            ':LABEL': 'E53_Place'
        })

    csd_places_df = pd.DataFrame(csd_places).drop_duplicates(subset=['place_id:ID'])
    csd_places_df.to_csv(out_dir / 'e53_place_csd.csv', index=False)
    print(f"  Wrote {len(csd_places_df)} E53_Place (CSD) nodes (persistent)")

    # CD Places: prefer the chain registry (one row per persistent CD chain
    # with canonical_name + years_active). Fall back to year-name CDs collected
    # during process_year if no chain registry is available.
    if cd_chain_registry_df is not None:
        cd_rows = []
        for _, row in cd_chain_registry_df.iterrows():
            cd_rows.append({
                'place_id:ID': row['place_id'],
                'place_type': 'CD',
                'name': row['canonical_name'],
                'province': row['province'],
                'years_active': row['years_active'],
                ':LABEL': 'E53_Place',
            })
        # Add singleton CDs that the chain pipeline missed (rare; e.g.,
        # CDs in years where the chain pipeline filtered them out).
        registered_chain_ids = set(cd_chain_registry_df['place_id'])
        for chain_id, name, prov in all_cd_places:
            if chain_id not in registered_chain_ids:
                cd_rows.append({
                    'place_id:ID': chain_id,
                    'place_type': 'CD',
                    'name': name,
                    'province': prov,
                    'years_active': '',
                    ':LABEL': 'E53_Place',
                })
        cd_places_df = pd.DataFrame(cd_rows).drop_duplicates(subset=['place_id:ID'])
    else:
        cd_places_df = pd.DataFrame([
            {'place_id:ID': cd_id, 'place_type': 'CD', 'name': name,
             'province': prov, 'years_active': '', ':LABEL': 'E53_Place'}
            for cd_id, name, prov in all_cd_places
        ])
    cd_places_df.to_csv(out_dir / 'e53_place_cd.csv', index=False)
    print(f"  Wrote {len(cd_places_df)} E53_Place (CD) nodes")

    # Copy CSD lineage file if it exists
    lineage_src = places_dir / "place_lineage.csv"
    if lineage_src.exists():
        lineage_df = pd.read_csv(lineage_src)
        lineage_df.to_csv(out_dir / 'place_lineage.csv', index=False)
        print(f"  Copied {len(lineage_df)} CSD lineage relationships")

    # Copy CD lineage file if it exists (Phase 1 output)
    cd_lineage_src = cd_chains_dir / "cd_lineage.csv"
    if cd_lineage_src.exists():
        cd_lineage_df = pd.read_csv(cd_lineage_src)
        cd_lineage_df.to_csv(out_dir / 'cd_lineage.csv', index=False)
        print(f"  Copied {len(cd_lineage_df)} CD lineage relationships")

    # Summary
    print(f"\n{'='*60}", file=sys.stderr)
    print(f"SUMMARY", file=sys.stderr)
    print(f"{'='*60}", file=sys.stderr)
    print(f"E53_Place (CSD): {len(csd_places_df):,} (persistent)", file=sys.stderr)
    print(f"  From registry: {len(registry_df):,}", file=sys.stderr)
    print(f"  Fallback singletons: {len(fallback_places):,}", file=sys.stderr)
    print(f"E53_Place (CD): {len(cd_places_df):,}", file=sys.stderr)
    print(f"E4_Period: {len(periods):,}", file=sys.stderr)
    print(f"E93_Presence: {total_stats['presences']:,}", file=sys.stderr)
    print(f"E94_Space_Primitive: {total_stats['space_primitives']:,}", file=sys.stderr)
    print(f"\nRelationships:", file=sys.stderr)
    print(f"P166_was_a_presence_of: {total_stats['p166']:,}", file=sys.stderr)
    print(f"P164_is_temporally_specified_by: {total_stats['p164']:,}", file=sys.stderr)
    print(f"P4_has_time-span (presence→E52): {total_stats['p4_time_span']:,}", file=sys.stderr)
    print(f"P161_has_spatial_projection: {total_stats['p161']:,}", file=sys.stderr)
    print(f"P122_borders_with (edges): {total_stats['p122_edges']:,}", file=sys.stderr)
    print(f"E16_Measurement (borders): {total_stats['border_measurements']:,}", file=sys.stderr)
    print(f"\nOutput: {out_dir}/", file=sys.stderr)


if __name__ == '__main__':
    main()
